### ISSUE TITLE
gem build is failing

### ISSUE THREAD

**Issue by nimkar** [oneops/cli#1]
Gem build fails with the error below.

WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["LICENSE"] are not files

FIX: Either remove the mention of LICENSE file from the Gemfile or (better) copy Apache2 License file here. I can create a pull request as soon as I sign your forms.

**Comment by sureshg** [comment]
Fixed as part of https://github.com/oneops/cli/pull/2
